### ISSUE TITLE
multiimpact_vcv

### ISSUE THREAD

**Issue by manorman5** [jrising/prospectus-tools#15] opened 2019-09-13 18:59 UTC
@mayaanorman question: what should my config file, which I need to add the `multiimpact_vcv` parameter to, look like? 

@jrising response: It should be a pathname. Start by generating a big block matrix which contains all of the other VCV matrices, including any covariance block or zeros if there is no covariance. Write this to a CSV, and tell me where I can find it to take a look.

**Comment by manorman5** [comment] 2019-09-13 19:01
@jrising here's a path to the full stacked regression vcv for the coefficients included in the csvv: `/shares/gcp/social/parameters/energy/incspline0719/GMFD/TINV_clim_income_spline/FD_FGLS_inter_climGMFD_Exclude_all-issues_break2_semi-parametric_poly2_OTHERIND_TINV_clim_income_spline.csv`

**Comment by jrising** [comment] 2019-09-19 08:36
Thanks. Next, where are the two sets of results that you want to combine?

**Comment by manorman5** [comment] 2019-09-19 14:30
Here is the path to the results we want to combine... just replace the * with either other_energy or electricity.
```
results-root: /shares/gcp/outputs/energy/impacts-blueghost/median_OTHERIND_*_TINV_clim_income_spline_GMFD
deltamethod: /shares/gcp/outputs/energy/impacts-blueghost/median_OTHERIND_*_TINV_clim_income_spline_GMFD_dm
```
Thanks James!

**Comment by brews** [comment] 2019-09-25 08:32
Here is an update:

We see the memory ramp up in the _second_ call to `results.sum_into_data()` here: https://github.com/jrising/prospectus-tools/blob/6539c912d61b7bd4e8b00ec3bfeb705c09d62b87/gcp/extract/quantiles.py#L41

Within this run of `results.sum_into_data()`, each loop adds roughly a GB to our memory footprint starting with `bundles.iterate_regions()` here: https://github.com/jrising/prospectus-tools/blob/6539c912d61b7bd4e8b00ec3bfeb705c09d62b87/gcp/extract/lib/results.py#L117

This is fine on any normal day because these memory allocations should be released once we're done with the data from each file. Buuuut, it looks like the memory is not being released/garbage collected, even once these loops are done. We'd need to look into `bundles.iterate_regions()` to see why it's so memory hungry.

@jrising, because you're familiar with the data, would you please have a look at:

1.  the files we're reading (I'm happy to provide the basenames or paths if you need) and be sure that the files are correct.
2. Ensure that `bundles.iterate_regions()` is extracting the region correctly and that the region data is not actually ~1 GB by accident.

I want to sanity check this before I do anything dramatic to the code.

**Comment by jrising** [comment] 2019-09-26 15:52
I don't think there's any surprise that it's in the reading of the deltamethod files that the memory boosts up: those files are really big. (As compared to the first call of sum_into_data, which is just reading the point estimate files).

There's also no smoking gun with the region name data. If you calculate the size of the deltamethod matrix, it should be ~0.9 GB, just like we see.

The problem is that this memory is not being released.

You mentioned that there is a working solution, if you limit the data before leaving the `read` function. I know that you want to get to some deep point of clarity on this, but it may not be worth the time, since there aren't obvious memory leaks in the projection system. Here is what I propose:

Leave `read` as it is, but add a `filter_regions` function which wraps each `read` command. `filter_regions` can take some of the logic currently in `iterate_regions` to select just the regions we want, and return the same arguments as `read`, but only for those regions. Then `iterate_regions` can still act as it currently does on this pared-down data.

**Comment by brews** [comment] 2019-09-26 17:42
@jrising Can do. Take a look here: https://github.com/brews/prospectus-tools/commit/708569303137ce20e18d3533ef1b26e93d8515e4

I think I called it `read_region()`.

I'm happy to draw this up into a PR if you'd like to run with it.

**Comment by brews** [comment] 2019-09-26 20:41
Note to self: I need to check this against case of users running it without 'region'/'regions' in their config.

**Comment by brews** [comment] 2019-09-27 13:46
I'm moving our discussion about the memory leak back over to issue #14.

@mayaanorman , you originally opened this with questions about `multiimpact_vcv`. Are you all set with that?

**Comment by manorman5** [comment] 2019-09-27 19:42
hey @brews, i'm just starting to test out the new system James set up for the multiimpact_vcv, so let's maybe keep this open until I wrap that up? Instead, I can also chat with James about that over email, if that is what you all prefer.

**Comment by brews** [comment] 2019-09-27 23:52
@mayaanorman, no sweat. Y'all can keep things rolling here. I'll keep this open if you still want to test things out.

**Comment by brews** [comment] 2019-10-08 17:36
I'm going to close this to keep things fresh.

If a new question/issue comes up please feel free to open a new issue and reference this.

**Closed as completed by brews** 2019-10-08 17:36 UTC
Labels: question
